{
 "title": "Kubernetes Node Dashboard",
 "description": "This dashboard monitors the health and performance of Kubernetes nodes, showcasing essential metrics such as CPU usage, RAM, disk space, and temperature. It allows teams to quickly identify potential issues and optimize resource allocation for improved system efficiency.",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "nodename",
    "query": {
     "query": "label_values(node_uname_info,nodename)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(node_uname_info{nodename=~\"$nodename\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$nodename", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "nodename" },
  {
   "title": "Total RAM",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{node=~\"$nodename\"})"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{node=~\"$nodename\", mode='system'})"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{node=\"$nodename\"} - node_memory_MemAvailable_bytes{node=\"$nodename\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_memory_MemTotal_bytes{node=~\"$nodename\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{node=~\"$nodename\", sensor=\"temp0\" }",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_filesystem_free_bytes{mountpoint!=\"/proc\", mountpoint!=\"/sys\", mountpoint!=\"/dev\", node=\"$nodename\"}) / 1073741824",
     "legendFormat": "__auto"
    },
    {
     "expr": "(sum(node_filesystem_size_bytes{mountpoint!=\"/proc\", mountpoint!=\"/sys\", mountpoint!=\"/dev\", node=\"$nodename\"}) \n-  sum(node_filesystem_free_bytes{mountpoint!=\"/proc\", mountpoint!=\"/sys\", mountpoint!=\"/dev\", node=\"$nodename\"})) \n/ 1073741824",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(time() - node_boot_time_seconds{node=~\"$nodename\"})"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{node=~\"$nodename\",sensor=\"temp0\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total[5m])) by (nodename)",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "kube_node_status_allocatable{resource=\"cpu\", node=~\"$nodename\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Red",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{node=\"$nodename\"}[5m])) by (node)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(node_network_receive_bytes_total{node=\"$nodename\"}[5m])) by (node)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{node=~\"$nodename\"} / node_memory_MemTotal_bytes{node=~\"$nodename\"})) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(instance) (rate(node_cpu_seconds_total{node=~\"$nodename\", mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}